name: CashSystem
version: '${version}'
main: org.hwabeag.cashsystem.CashSystem
api-version: '1.21'
softdepend: [PlaceholderAPI]

commands:
  캐시:
    description: 캐시 명령어입니다.
    usage: /캐시
  캐시상점:
    description: 캐시상점 명령어입니다.
    usage: /캐시상점
  금액:
    description: 금액 설정 명령어입니다.
    usage: /금액
